version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    command: >
      sh -c "/scripts/wait-for-it.sh db:5432 --
        uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  test:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    command: >
      sh -c "/scripts/wait-for-it.sh db:5432 --
        pytest /app/tests"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: