version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  proxy:
    build:
      context: ./proxy
    restart: unless-stopped
    image: proxy
    container_name: proxy
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - app

    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: