version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=${DEV}
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "/scripts/wait-for-it.sh db:5432 &&
        uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEV_POSTGRES_DB}
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}

volumes:
  dev-db-data:
